name: Publish newest GEOEXIF build

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Set env
        run: echo "GH_TOKEN=${{ secrets.github_token }}" >> $GITHUB_ENV
      - name: Build/release Electron app
        run: npm deploy-app